import React from "react";
import PropTypes from "prop-types";

/**
 * Base HTML wrapper for pages generated by Gatsby.
 * Ported from Views/Shared/_Layout.cshtml in legacy MVC application.
 *
 * @param props Gatsby initialization props.
 * @returns React element containing the base HTML framework.
 */
const HTML = (props) => {
  return (
    <html
      {...props.htmlAttributes}
      className=" js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms no-csstransforms3d csstransitions fontface no-generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths"
    >
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>
          {!!props.title ? props.title + " - " : ""}Magenic Automation Test Site
        </title>
        <link rel="icon" href="/Content/favicon.ico" />
        {props.headComponents}
      </head>
      {props.preBodyComponents}
      <body id="___gatsby" dangerouslySetInnerHTML={{ __html: props.body }} />
      {props.postBodyComponents}
    </html>
  );
};

export default HTML;

HTML.propTypes = {
  htmlAttributes: PropTypes.object,
  headComponents: PropTypes.array,
  bodyAttributes: PropTypes.object,
  preBodyComponents: PropTypes.array,
  body: PropTypes.string,
  postBodyComponents: PropTypes.array,
};
